/** SitePack catalog — Motionsites-shaped gallery, ZIP source packs
 *  Catalog trim 2026-10-01 PT (Bret remove pass 2). Packaged: 60
 *  Removed: fable-25 hub, lumora, lumora-omega, omniscience-radar, theshadow, the-website
 *  Kept: individual fable-* demo packs; prior exclusions unchanged
 */

export const FILTERS = [
  'All',
  'Landing',
  'SaaS',
  'Agency',
  'Portfolio',
  'Film',
  'Entertainment',
  'Coaching',
  'Services',
  'Design-Build',
  'Creative',
]

export const PACKS = [
  {
    id: "dcrbn",
    slug: "dcrbn",
    title: "DCRBN",
    category: "Film",
    filters: ["Landing", "Creative"],
    tagline: "DCRBN alias project (dcrbn.vercel.app)",
    demo: "https://dcrbn.vercel.app",
    poster: "/posters/dcrbn.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:bret1976/dcrbn-io",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb923c",
    featured: true,
    tall: true,
  },
  {
    id: "jmi-entertainment",
    slug: "jmi-entertainment",
    title: "JMI Entertainment",
    category: "Entertainment",
    filters: ["Landing", "Creative"],
    tagline: "JMI Entertainment client marketing site",
    demo: "https://jmi-entertainment.vercel.app",
    poster: "/posters/jmi-entertainment.jpg",
    price: 49,
    stack: "Project source",
    source: "repo:bret1976/jmi-entertainment",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e8ff6b",
    featured: true,
    tall: true,
  },
  {
    id: "kanek-frames",
    slug: "kanek-frames",
    title: "Kanek Frames",
    category: "Landing",
    filters: ["Landing", "Film", "Creative"],
    tagline: "KANEK FRAMES — intelligence built into structure (WebFetch OK)",
    demo: "https://kanek-frames.vercel.app",
    poster: "/posters/kanek-frames.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:bret1976/kanek-frames",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#c4b5fd",
    featured: true,
    tall: true,
  },
  {
    id: "north-and-mercer",
    slug: "north-and-mercer",
    title: "North & Mercer",
    category: "Design-Build",
    filters: ["Landing", "Creative"],
    tagline: "NORTH & MERCER interior design firm site (WebFetch OK)",
    demo: "https://north-and-mercer.vercel.app",
    poster: "/posters/north-and-mercer.jpg",
    price: 49,
    stack: "Static capture",
    source: "static-capture",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
    featured: true,
    tall: true,
  },
  {
    id: "parallel-cinema",
    slug: "parallel-cinema",
    title: "Parallel Cinema",
    category: "Film",
    filters: ["Landing", "Film", "Creative"],
    tagline: "Parallel Cinema interactive landing",
    demo: "https://parallel-cinema.vercel.app",
    poster: "/posters/parallel-cinema.jpg",
    price: 49,
    stack: "Static HTML",
    source: "repo:VegasCryptoAgent/parallel-cinema",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
    featured: true,
    tall: true,
  },
  {
    id: "still-theory-studio",
    slug: "still-theory-studio",
    title: "Still Theory Studio",
    category: "Film",
    filters: ["Landing", "Film", "Agency", "Creative"],
    tagline: "Still Theory Studio cinematic marketing site",
    demo: "https://still-theory-studio.vercel.app",
    poster: "/posters/still-theory-studio.jpg",
    price: 49,
    stack: "Project source",
    source: "repo:bret1976/still-theory-studio",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#67e8f9",
    featured: true,
    tall: true,
  },
  {
    id: "the-bret-akari",
    slug: "the-bret-akari",
    title: "Bret Akari",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Bret Akari personal/character site",
    demo: "https://the-bret-akari.vercel.app",
    poster: "/posters/the-bret-akari.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#67e8f9",
  },
  {
    id: "bret-jenny-minh-clone",
    slug: "bret-jenny-minh-clone",
    title: "Bret Jenny Minh",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Bret/Jenny/Minh clone landing",
    demo: "https://bret-jenny-minh-clone.vercel.app",
    poster: "/posters/bret-jenny-minh-clone.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#f9a8d4",
  },
  {
    id: "cold-shine",
    slug: "cold-shine",
    title: "Cold Shine",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Cold Shine site/app",
    demo: "https://cold-shine.vercel.app",
    poster: "/posters/cold-shine.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:bret1976/cold-shine",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#93c5fd",
    tall: true,
  },
  {
    id: "commerce-dispatch-winter-shift",
    slug: "commerce-dispatch-winter-shift",
    title: "Commerce Dispatch",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Commerce Dispatch winter-shift landing",
    demo: "https://commerce-dispatch-winter-shift.vercel.app",
    poster: "/posters/commerce-dispatch-winter-shift.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
  },
  {
    id: "cory-warfield-coaching-site",
    slug: "cory-warfield-coaching-site",
    title: "Cory Warfield Coaching",
    category: "Coaching",
    filters: ["Landing", "Coaching", "Creative"],
    tagline: "Cory Warfield coaching landing",
    demo: "https://cory-warfield-coaching-site.vercel.app",
    poster: "/posters/cory-warfield-coaching-site.jpg",
    price: 49,
    stack: "Project source",
    source: "repo:VegasCryptoAgent/cory-warfield-coaching-site",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
  },
  {
    id: "daysole",
    slug: "daysole",
    title: "Daysole",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Daysole brand landing",
    demo: "https://daysole.vercel.app",
    poster: "/posters/daysole.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb923c",
  },
  {
    id: "fooh-kit",
    slug: "fooh-kit",
    title: "FOOH Kit",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "FOOH kit marketing/demo",
    demo: "https://fooh-kit.vercel.app",
    poster: "/posters/fooh-kit.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#67e8f9",
  },
  {
    id: "kabuto-clone",
    slug: "kabuto-clone",
    title: "Kabuto Edomae",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Kabuto Edomae Framer clone",
    demo: "https://kabuto-clone.vercel.app",
    poster: "/posters/kabuto-clone.jpg",
    price: 49,
    stack: "Static HTML",
    source: "repo:VegasCryptoAgent/kabuto-edomae-framer-clone",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff7a59",
  },
  {
    id: "kanek",
    slug: "kanek",
    title: "Kanek",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Kanek primary OS/landing",
    demo: "https://kanek.vercel.app",
    poster: "/posters/kanek.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#86efac",
  },
  {
    id: "majid-zafer-astrodither",
    slug: "majid-zafer-astrodither",
    title: "Majid Zafer Astrodither",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Majid Zafer Astrodither art site",
    demo: "https://majid-zafer-astrodither.vercel.app",
    poster: "/posters/majid-zafer-astrodither.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:VegasCryptoAgent/majid-zafer-astrodither",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#f9a8d4",
  },
  {
    id: "manifest-neuve",
    slug: "manifest-neuve",
    title: "Manifest Neuve",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Manifest Neuve brand landing",
    demo: "https://manifest-neuve.vercel.app",
    poster: "/posters/manifest-neuve.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb7185",
  },
  {
    id: "moment-path",
    slug: "moment-path",
    title: "Moment Path",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Moment Path 3D memory/time-capsule",
    demo: "https://moment-path.vercel.app",
    poster: "/posters/moment-path.jpg",
    price: 49,
    stack: "Static HTML",
    source: "repo:VegasCryptoAgent/moment-path",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb7185",
  },
  {
    id: "new-web-design",
    slug: "new-web-design",
    title: "New Web Design",
    category: "Landing",
    filters: ["Landing", "Agency", "Creative"],
    tagline: "New web design experiment",
    demo: "https://new-web-design.vercel.app",
    poster: "/posters/new-web-design.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#93c5fd",
  },
  {
    id: "penguin-inc",
    slug: "penguin-inc",
    title: "Penguin Inc",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Penguin Inc brand landing",
    demo: "https://penguin-inc.vercel.app",
    poster: "/posters/penguin-inc.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb923c",
  },
  {
    id: "rolls-royce-las-vegas-luxury-site",
    slug: "rolls-royce-las-vegas-luxury-site",
    title: "Rolls-Royce Las Vegas",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Rolls-Royce Las Vegas luxury marketing",
    demo: "https://rolls-royce-las-vegas-luxury-site.vercel.app",
    poster: "/posters/rolls-royce-las-vegas-luxury-site.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#a1a1aa",
  },
  {
    id: "shotline",
    slug: "shotline",
    title: "Shotline",
    category: "SaaS",
    filters: ["SaaS", "Creative", "Landing"],
    tagline: "Shotline production tool",
    demo: "https://shotline.vercel.app",
    poster: "/posters/shotline.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#94a3b8",
  },
  {
    id: "ultra-mode",
    slug: "ultra-mode",
    title: "Ultra Mode",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "UltraMode cool landing page",
    demo: "https://ultra-mode.vercel.app",
    poster: "/posters/ultra-mode.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:VegasCryptoAgent/UltraMode",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#7dd3fc",
  },
  {
    id: "fable-aurora",
    slug: "fable-aurora",
    title: "Fable · Auroré",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "WebGL aurora shader · luxury fragrance (Fable × 25 #01)",
    demo: "https://fable-25-ruby.vercel.app/01-aurora/",
    poster: "/posters/fable-aurora.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#7fffd4",
    featured: true,
  },
  {
    id: "fable-monolith",
    slug: "fable-monolith",
    title: "Fable · Monolith",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Three.js refractive crystal · museum of one (Fable × 25 #02)",
    demo: "https://fable-25-ruby.vercel.app/02-monolith/",
    poster: "/posters/fable-monolith.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#9fc4ff",
    featured: true,
  },
  {
    id: "fable-brut",
    slug: "fable-brut",
    title: "Fable · BRUT*",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Brutalist type · design collective (Fable × 25 #03)",
    demo: "https://fable-25-ruby.vercel.app/03-brut/",
    poster: "/posters/fable-brut.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff2e00",
    featured: true,
  },
  {
    id: "fable-helvetia",
    slug: "fable-helvetia",
    title: "Fable · Studio Helvetia",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Swiss grid · International Style (Fable × 25 #04)",
    demo: "https://fable-25-ruby.vercel.app/04-helvetia/",
    poster: "/posters/fable-helvetia.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e30613",
    featured: true,
  },
  {
    id: "fable-verse",
    slug: "fable-verse",
    title: "Fable · Verse",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Kinetic typography · a poem you scroll (Fable × 25 #05)",
    demo: "https://fable-25-ruby.vercel.app/05-verse/",
    poster: "/posters/fable-verse.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e8a33d",
    featured: true,
  },
  {
    id: "fable-stellar",
    slug: "fable-stellar",
    title: "Fable · Stellar Cartography",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "1,400 living particles · invented constellations (Fable × 25 #06)",
    demo: "https://fable-25-ruby.vercel.app/06-stellar/",
    poster: "/posters/fable-stellar.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ffd9a0",
  },
  {
    id: "fable-terminal",
    slug: "fable-terminal",
    title: "Fable · OBSOLETE.SYS",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Working CRT terminal · museum of dead machines (Fable × 25 #07)",
    demo: "https://fable-25-ruby.vercel.app/07-terminal/",
    poster: "/posters/fable-terminal.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#5cff8f",
  },
  {
    id: "fable-ma",
    slug: "fable-ma",
    title: "Fable · 間 — Ma",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Japanese negative space · four seasons (Fable × 25 #08)",
    demo: "https://fable-25-ruby.vercel.app/08-ma/",
    poster: "/posters/fable-ma.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#b23a2f",
  },
  {
    id: "fable-gatsby",
    slug: "fable-gatsby",
    title: "Fable · The Meridian",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Art Deco grand hotel · gilded SVG (Fable × 25 #09)",
    demo: "https://fable-25-ruby.vercel.app/09-gatsby/",
    poster: "/posters/fable-gatsby.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#c9a24b",
  },
  {
    id: "fable-bauhaus",
    slug: "fable-bauhaus",
    title: "Fable · Spielplatz",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Bauhaus playground · draggable physics (Fable × 25 #10)",
    demo: "https://fable-25-ruby.vercel.app/10-bauhaus/",
    poster: "/posters/fable-bauhaus.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#f2b705",
  },
  {
    id: "fable-lumen",
    slug: "fable-lumen",
    title: "Fable · Lumen",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Organic gradient blobs · soft SaaS (Fable × 25 #11)",
    demo: "https://fable-25-ruby.vercel.app/11-lumen/",
    poster: "/posters/fable-lumen.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e88a6a",
  },
  {
    id: "fable-gazette",
    slug: "fable-gazette",
    title: "Fable · The Evening Gazette",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "1890s broadsheet · pure letterpress (Fable × 25 #12)",
    demo: "https://fable-25-ruby.vercel.app/12-gazette/",
    poster: "/posters/fable-gazette.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#8a7a5c",
  },
  {
    id: "fable-neon-district",
    slug: "fable-neon-district",
    title: "Fable · Neon District",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Cyberpunk glitch · techwear lookbook (Fable × 25 #13)",
    demo: "https://fable-25-ruby.vercel.app/13-neon-district/",
    poster: "/posters/fable-neon-district.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#00f0ff",
  },
  {
    id: "fable-storybook",
    slug: "fable-storybook",
    title: "Fable · The Snail Who Mailed Herself",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Watercolor storybook · SVG illustration (Fable × 25 #14)",
    demo: "https://fable-25-ruby.vercel.app/14-storybook/",
    poster: "/posters/fable-storybook.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e8a3a3",
  },
  {
    id: "fable-atelier",
    slug: "fable-atelier",
    title: "Fable · Atelier Grau",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Monochrome architecture · layered parallax (Fable × 25 #15)",
    demo: "https://fable-25-ruby.vercel.app/15-atelier/",
    poster: "/posters/fable-atelier.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#9b9b9b",
  },
  {
    id: "fable-pulse",
    slug: "fable-pulse",
    title: "Fable · Pulse//Metropolis",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Six living charts · data as ornament (Fable × 25 #16)",
    demo: "https://fable-25-ruby.vercel.app/16-pulse/",
    poster: "/posters/fable-pulse.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#4ecdc4",
  },
  {
    id: "fable-daydream",
    slug: "fable-daydream",
    title: "Fable · Daydream Plaza™",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Vaporwave mall · open 3–4 a.m. only (Fable × 25 #17)",
    demo: "https://fable-25-ruby.vercel.app/17-daydream/",
    poster: "/posters/fable-daydream.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff71ce",
  },
  {
    id: "fable-radiola",
    slug: "fable-radiola",
    title: "Fable · Radiola 7",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Skeuomorphic radio · real Web Audio synthesis (Fable × 25 #18)",
    demo: "https://fable-25-ruby.vercel.app/18-radiola/",
    poster: "/posters/fable-radiola.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ffb347",
  },
  {
    id: "fable-odyssey",
    slug: "fable-odyssey",
    title: "Fable · Odyssey",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Solar system scrollytelling · canvas planets (Fable × 25 #19)",
    demo: "https://fable-25-ruby.vercel.app/19-odyssey/",
    poster: "/posters/fable-odyssey.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#7fb4ff",
  },
  {
    id: "fable-ascii",
    slug: "fable-ascii",
    title: "Fable · Glyphwerk",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Real-time ASCII engine · 3D in characters (Fable × 25 #20)",
    demo: "https://fable-25-ruby.vercel.app/20-ascii/",
    poster: "/posters/fable-ascii.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#7fdc6f",
  },
  {
    id: "fable-herbarium",
    slug: "fable-herbarium",
    title: "Fable · Herbarium Perdita",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Engraved botany · plants that never were (Fable × 25 #21)",
    demo: "https://fable-25-ruby.vercel.app/21-herbarium/",
    poster: "/posters/fable-herbarium.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#5d6b4a",
  },
  {
    id: "fable-synth",
    slug: "fable-synth",
    title: "Fable · Polyphon",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Playable synthesizer · reactive visuals (Fable × 25 #22)",
    demo: "https://fable-25-ruby.vercel.app/22-synth/",
    poster: "/posters/fable-synth.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#9d7bff",
  },
  {
    id: "fable-flux",
    slug: "fable-flux",
    title: "Fable · Flux",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Seeded generative gallery · eight algorithms (Fable × 25 #23)",
    demo: "https://fable-25-ruby.vercel.app/23-flux/",
    poster: "/posters/fable-flux.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e2543e",
  },
  {
    id: "fable-codex",
    slug: "fable-codex",
    title: "Fable · Codex Luminis",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Illuminated manuscript · gold leaf in CSS (Fable × 25 #24)",
    demo: "https://fable-25-ruby.vercel.app/24-codex/",
    poster: "/posters/fable-codex.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#b8860b",
  },
  {
    id: "fable-chrome",
    slug: "fable-chrome",
    title: "Fable · Chrome2000",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Y2K liquid metal · per-pixel metaballs (Fable × 25 #25)",
    demo: "https://fable-25-ruby.vercel.app/25-chrome/",
    poster: "/posters/fable-chrome.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#8ff0ff",
  },
  {
    id: "fable-axiom",
    slug: "fable-axiom",
    title: "Fable · Axiom",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "AI SaaS platform · cursor spotlight, pinned feature theater (Fable × 25 #26)",
    demo: "https://fable-25-ruby.vercel.app/26-axiom/",
    poster: "/posters/fable-axiom.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#7c5cff",
  },
  {
    id: "fable-chronos",
    slug: "fable-chronos",
    title: "Fable · Chronos Atelier",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Haute horlogerie · scroll-assembled watch, horizontal rail (Fable × 25 #27)",
    demo: "https://fable-25-ruby.vercel.app/27-chronos/",
    poster: "/posters/fable-chronos.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#d4b06a",
  },
  {
    id: "fable-vanta",
    slug: "fable-vanta",
    title: "Fable · Vanta",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Fintech infrastructure · Three.js particle Earth, live rails (Fable × 25 #28)",
    demo: "https://fable-25-ruby.vercel.app/28-vanta/",
    poster: "/posters/fable-vanta.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#2ee6a8",
  },
  {
    id: "fable-kine",
    slug: "fable-kine",
    title: "Fable · KINE®",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Motion studio · velocity-reactive type, cursor previews (Fable × 25 #29)",
    demo: "https://fable-25-ruby.vercel.app/29-kine/",
    poster: "/posters/fable-kine.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff4d00",
  },
  {
    id: "fable-ascent",
    slug: "fable-ascent",
    title: "Fable · Ascent Equipment",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Expedition apparel · parallax range, altitude scrollytelling (Fable × 25 #30)",
    demo: "https://fable-25-ruby.vercel.app/30-ascent/",
    poster: "/posters/fable-ascent.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff5a1f",
  },
  {
    id: "fable-orbital",
    slug: "fable-orbital",
    title: "Fable · Orbital",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Space hotel · scroll-driven NASA film, statement type (Fable × 25 #31)",
    demo: "https://fable-25-ruby.vercel.app/31-orbital/",
    poster: "/posters/fable-orbital.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#9db8ff",
  },
  {
    id: "fable-eidolon",
    slug: "fable-eidolon",
    title: "Fable · Eidolon",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Dreamworld atelier · JWST worlds, glass reels (Fable × 25 #32)",
    demo: "https://fable-25-ruby.vercel.app/32-eidolon/",
    poster: "/posters/fable-eidolon.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#c9b8ff",
  },
  {
    id: "fable-ember",
    slug: "fable-ember",
    title: "Fable · Ember Elite",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Product theater · live 3D basketball, drag to spin (Fable × 25 #33)",
    demo: "https://fable-25-ruby.vercel.app/33-ember/",
    poster: "/posters/fable-ember.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff4d12",
  },
  {
    id: "fable-casa",
    slug: "fable-casa",
    title: "Fable · Casa.",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Architecture journal · Muralla Roja, sticky study (Fable × 25 #34)",
    demo: "https://fable-25-ruby.vercel.app/34-casa/",
    poster: "/posters/fable-casa.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#b8302a",
  },
  {
    id: "fable-nocturne",
    slug: "fable-nocturne",
    title: "Fable · Nocturne",
    category: "Creative",
    filters: ["Landing", "Creative"],
    tagline: "Night film house · full-screen scene wipes (Fable × 25 #35)",
    demo: "https://fable-25-ruby.vercel.app/35-nocturne/",
    poster: "/posters/fable-nocturne.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (Fable × 25)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#57e8e0",
  },
  {
    id: "vence-jewelry",
    slug: "vence-jewelry",
    title: "Vence Jewelry",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Vence jewelry brand landing",
    demo: "https://vence-jewelry.vercel.app/",
    poster: "/posters/vence-jewelry.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e8c39e",
    featured: true,
  },
  {
    id: "hewn-six",
    slug: "hewn-six",
    title: "HEWN SIX",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "HEWN SIX — distinct Hewn variant (re-added)",
    demo: "https://hewn-six.vercel.app/",
    poster: "/posters/hewn-six.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#c4a574",
    featured: true,
    tall: true,
  },
]

/** Keep a few coming-soon tiles for density; real packs dominate. */
export const PLACEHOLDERS = [
]

export const GALLERY = [...PACKS, ...PLACEHOLDERS]

export const ALL_ACCESS = {
  id: 'all-access',
  slug: 'all-access',
  title: 'All-Access',
  price: 149,
  compareAt: 3136,
  tagline: 'Unlock all SitePack sources in one purchase.',
}

export const PLANS = [
  {
    id: 'yearly',
    name: 'Yearly Access',
    subtitle: 'All packs + updates for a year',
    price: 99,
    period: 'Per year, cancel anytime',
    cta: 'Subscribe Yearly',
    packId: 'all-access',
    features: ['All current SitePack ZIPs','New packs added during the year','Personal & client work','Priority support'],
  },
  {
    id: 'lifetime',
    name: 'Lifetime Access',
    subtitle: 'All packs, forever',
    price: 149,
    compareAt: 3136,
    period: 'One-time payment',
    cta: 'Pay once, unlock forever',
    popular: true,
    packId: 'all-access',
    features: ['All current SitePack ZIPs','Lifetime updates to the library','Personal & client work','Priority support','Early access to new drops'],
  },
]

export const DEMO_UNLOCK_CODE = 'SITEPACK-DEMO-2026'

export const STRIPE_LINKS = {
  'dcrbn': '',
  'hewn': '',
  'jmi-entertainment': '',
  'kanek-frames': '',
  'north-and-mercer': '',
  'parallel-cinema': '',
  'still-theory-studio': '',
  '6frame-media': '',
  '6frame-motion-portfolio': '',
  '6-frame': '',
  '6-frame-studio-price': '',
  'ai-content-system': '',
  'architect-pro': '',
  'archivist': '',
  'the-bret-akari': '',
  'bret-jenny-minh-clone': '',
  'cinema-vault': '',
  'cinematic-ai-playbook-interactive': '',
  'clipforge': '',
  'cold-shine': '',
  'commerce-dispatch-winter-shift': '',
  'cory-warfield-coaching-site': '',
  'daysole': '',
  'dembrandt-studio': '',
  'elva-labs-clone': '',
  'fooh-kit': '',
  'frames': '',
  'fusion-layer': '',
  'gemini-casino-v2': '',
  'gemini-xr-full': '',
  'h3-studio': '',
  'housebrain': '',
  'ian-group-video-intro': '',
  'iron-sights': '',
  'kabuto-clone': '',
  'kanek': '',
  'kanek-ai-host': '',
  'kanek-horror-house': '',
  'lockframe': '',
  'majid-zafer-astrodither': '',
  'manifest-neuve': '',
  'moment-path': '',
  'new-web-design': '',
  'penguin-inc': '',
  'pryme': '',
  'pryme-website': '',
  'rolls-royce-las-vegas-luxury-site': '',
  'shot-synth': '',
  'shotline': '',
  'site-takeover-6frame': '',
  'starchild': '',
  'starling': '',
  'ultra-mode': '',
  'vence': '',
  'viberator': '',
  'viberator2': '',
  'warview-final-v2': '',
  'worldmonitor': '',
  'your-fresh-start-solutions': '',
  'fable-aurora': '',
  'fable-monolith': '',
  'fable-brut': '',
  'fable-helvetia': '',
  'fable-verse': '',
  'fable-stellar': '',
  'fable-terminal': '',
  'fable-ma': '',
  'fable-gatsby': '',
  'fable-bauhaus': '',
  'fable-lumen': '',
  'fable-gazette': '',
  'fable-neon-district': '',
  'fable-storybook': '',
  'fable-atelier': '',
  'fable-pulse': '',
  'fable-daydream': '',
  'fable-radiola': '',
  'fable-odyssey': '',
  'fable-ascii': '',
  'fable-herbarium': '',
  'fable-synth': '',
  'fable-flux': '',
  'fable-codex': '',
  'fable-chrome': '',
  'fable-axiom': '',
  'fable-chronos': '',
  'fable-vanta': '',
  'fable-kine': '',
  'fable-ascent': '',
  'fable-orbital': '',
  'fable-eidolon': '',
  'fable-ember': '',
  'fable-casa': '',
  'fable-nocturne': '',
  'vence-jewelry': '',
  'hewn-six': '',
  'all-access': '',
}

/** Prefer GitHub Release assets when available; otherwise /packs/<id>.zip (local/dev). */
const RELEASE = 'https://github.com/bret1976/sitepack/releases/download/v1.0.0'
const RELEASE_IDS = new Set([
'still-theory-studio',
  'jmi-entertainment',
  'starling',
  'cory-warfield-coaching-site',
  'your-fresh-start-solutions',
  'north-and-mercer',
  '6frame-rate-website',
  'fable-aurora',
  'fable-monolith',
  'fable-brut',
  'fable-helvetia',
  'fable-verse',
  'fable-stellar',
  'fable-terminal',
  'fable-ma',
  'fable-gatsby',
  'fable-bauhaus',
  'fable-lumen',
  'fable-gazette',
  'fable-neon-district',
  'fable-storybook',
  'fable-atelier',
  'fable-pulse',
  'fable-daydream',
  'fable-radiola',
  'fable-odyssey',
  'fable-ascii',
  'fable-herbarium',
  'fable-synth',
  'fable-flux',
  'fable-codex',
  'fable-chrome',
  'fable-axiom',
  'fable-chronos',
  'fable-vanta',
  'fable-kine',
  'fable-ascent',
  'fable-orbital',
  'fable-eidolon',
  'fable-ember',
  'fable-casa',
  'fable-nocturne',
  'vence-jewelry',
  'hewn-six',
  'penguin-inc',
  'moment-path',
])

export function packZipPath(id) {
  if (id === 'all-access') return null
  if (RELEASE_IDS.has(id)) return `${RELEASE}/${id}.zip`
  return `/packs/${id}.zip`
}

