/** SitePack catalog — Motionsites-shaped gallery, ZIP source packs
 *  Catalog trim 2026-10-01 PT. Packaged: 28 · Excluded: 6framerates + ManySides + Bret remove-list (2026-09-30 + 2026-10-01)
 */

export const FILTERS = [
  'All',
  'Landing',
  'SaaS',
  'Agency',
  'Portfolio',
  'Film',
  'Entertainment',
  'Coaching',
  'Services',
  'Design-Build',
  'Creative',
]

export const PACKS = [
  {
    id: "dcrbn",
    slug: "dcrbn",
    title: "DCRBN",
    category: "Film",
    filters: ["Landing", "Creative"],
    tagline: "DCRBN alias project (dcrbn.vercel.app)",
    demo: "https://dcrbn.vercel.app",
    poster: "/posters/dcrbn.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:bret1976/dcrbn-io",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb923c",
    featured: true,
    tall: true,
  },
  {
    id: "jmi-entertainment",
    slug: "jmi-entertainment",
    title: "JMI Entertainment",
    category: "Entertainment",
    filters: ["Landing", "Creative"],
    tagline: "JMI Entertainment client marketing site",
    demo: "https://jmi-entertainment.vercel.app",
    poster: "/posters/jmi-entertainment.jpg",
    price: 49,
    stack: "Project source",
    source: "repo:bret1976/jmi-entertainment",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e8ff6b",
    featured: true,
    tall: true,
  },
  {
    id: "kanek-frames",
    slug: "kanek-frames",
    title: "Kanek Frames",
    category: "Landing",
    filters: ["Landing", "Film", "Creative"],
    tagline: "KANEK FRAMES — intelligence built into structure (WebFetch OK)",
    demo: "https://kanek-frames.vercel.app",
    poster: "/posters/kanek-frames.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:bret1976/kanek-frames",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#c4b5fd",
    featured: true,
    tall: true,
  },
  {
    id: "north-and-mercer",
    slug: "north-and-mercer",
    title: "North & Mercer",
    category: "Design-Build",
    filters: ["Landing", "Creative"],
    tagline: "NORTH & MERCER interior design firm site (WebFetch OK)",
    demo: "https://north-and-mercer.vercel.app",
    poster: "/posters/north-and-mercer.jpg",
    price: 49,
    stack: "Static capture",
    source: "static-capture",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
    featured: true,
    tall: true,
  },
  {
    id: "parallel-cinema",
    slug: "parallel-cinema",
    title: "Parallel Cinema",
    category: "Film",
    filters: ["Landing", "Film", "Creative"],
    tagline: "Parallel Cinema interactive landing",
    demo: "https://parallel-cinema.vercel.app",
    poster: "/posters/parallel-cinema.jpg",
    price: 49,
    stack: "Static HTML",
    source: "repo:VegasCryptoAgent/parallel-cinema",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
    featured: true,
    tall: true,
  },
  {
    id: "still-theory-studio",
    slug: "still-theory-studio",
    title: "Still Theory Studio",
    category: "Film",
    filters: ["Landing", "Film", "Agency", "Creative"],
    tagline: "Still Theory Studio cinematic marketing site",
    demo: "https://still-theory-studio.vercel.app",
    poster: "/posters/still-theory-studio.jpg",
    price: 49,
    stack: "Project source",
    source: "repo:bret1976/still-theory-studio",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#67e8f9",
    featured: true,
    tall: true,
  },
  {
    id: "the-bret-akari",
    slug: "the-bret-akari",
    title: "Bret Akari",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Bret Akari personal/character site",
    demo: "https://the-bret-akari.vercel.app",
    poster: "/posters/the-bret-akari.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#67e8f9",
  },
  {
    id: "bret-jenny-minh-clone",
    slug: "bret-jenny-minh-clone",
    title: "Bret Jenny Minh",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Bret/Jenny/Minh clone landing",
    demo: "https://bret-jenny-minh-clone.vercel.app",
    poster: "/posters/bret-jenny-minh-clone.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#f9a8d4",
  },
  {
    id: "cold-shine",
    slug: "cold-shine",
    title: "Cold Shine",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Cold Shine site/app",
    demo: "https://cold-shine.vercel.app",
    poster: "/posters/cold-shine.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:bret1976/cold-shine",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#93c5fd",
    tall: true,
  },
  {
    id: "commerce-dispatch-winter-shift",
    slug: "commerce-dispatch-winter-shift",
    title: "Commerce Dispatch",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Commerce Dispatch winter-shift landing",
    demo: "https://commerce-dispatch-winter-shift.vercel.app",
    poster: "/posters/commerce-dispatch-winter-shift.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
  },
  {
    id: "cory-warfield-coaching-site",
    slug: "cory-warfield-coaching-site",
    title: "Cory Warfield Coaching",
    category: "Coaching",
    filters: ["Landing", "Coaching", "Creative"],
    tagline: "Cory Warfield coaching landing",
    demo: "https://cory-warfield-coaching-site.vercel.app",
    poster: "/posters/cory-warfield-coaching-site.jpg",
    price: 49,
    stack: "Project source",
    source: "repo:VegasCryptoAgent/cory-warfield-coaching-site",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#bef264",
  },
  {
    id: "daysole",
    slug: "daysole",
    title: "Daysole",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Daysole brand landing",
    demo: "https://daysole.vercel.app",
    poster: "/posters/daysole.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb923c",
  },
  {
    id: "fable-25",
    slug: "fable-25",
    title: "Fable 25",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Fable 25 brand/product landing",
    demo: "https://fable-25.vercel.app",
    poster: "/posters/fable-25.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#94a3b8",
  },
  {
    id: "fooh-kit",
    slug: "fooh-kit",
    title: "FOOH Kit",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "FOOH kit marketing/demo",
    demo: "https://fooh-kit.vercel.app",
    poster: "/posters/fooh-kit.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#67e8f9",
  },
  {
    id: "kabuto-clone",
    slug: "kabuto-clone",
    title: "Kabuto Edomae",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Kabuto Edomae Framer clone",
    demo: "https://kabuto-clone.vercel.app",
    poster: "/posters/kabuto-clone.jpg",
    price: 49,
    stack: "Static HTML",
    source: "repo:VegasCryptoAgent/kabuto-edomae-framer-clone",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff7a59",
  },
  {
    id: "kanek",
    slug: "kanek",
    title: "Kanek",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Kanek primary OS/landing",
    demo: "https://kanek.vercel.app",
    poster: "/posters/kanek.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#86efac",
  },
  {
    id: "lumora",
    slug: "lumora",
    title: "Lumora",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Lumora brand landing",
    demo: "https://lumora.vercel.app",
    poster: "/posters/lumora.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#f9a8d4",
    tall: true,
  },
  {
    id: "majid-zafer-astrodither",
    slug: "majid-zafer-astrodither",
    title: "Majid Zafer Astrodither",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Majid Zafer Astrodither art site",
    demo: "https://majid-zafer-astrodither.vercel.app",
    poster: "/posters/majid-zafer-astrodither.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:VegasCryptoAgent/majid-zafer-astrodither",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#f9a8d4",
  },
  {
    id: "manifest-neuve",
    slug: "manifest-neuve",
    title: "Manifest Neuve",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Manifest Neuve brand landing",
    demo: "https://manifest-neuve.vercel.app",
    poster: "/posters/manifest-neuve.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb7185",
  },
  {
    id: "moment-path",
    slug: "moment-path",
    title: "Moment Path",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Moment Path 3D memory/time-capsule",
    demo: "https://moment-path.vercel.app",
    poster: "/posters/moment-path.jpg",
    price: 49,
    stack: "Static HTML",
    source: "repo:VegasCryptoAgent/moment-path",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb7185",
  },
  {
    id: "new-web-design",
    slug: "new-web-design",
    title: "New Web Design",
    category: "Landing",
    filters: ["Landing", "Agency", "Creative"],
    tagline: "New web design experiment",
    demo: "https://new-web-design.vercel.app",
    poster: "/posters/new-web-design.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#93c5fd",
  },
  {
    id: "omniscience-radar",
    slug: "omniscience-radar",
    title: "Omniscience Radar",
    category: "SaaS",
    filters: ["SaaS", "Creative", "Landing"],
    tagline: "Omniscience Radar cosmic dashboard",
    demo: "https://omniscience-radar.vercel.app",
    poster: "/posters/omniscience-radar.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:VegasCryptoAgent/Omniscience-Radar",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#93c5fd",
  },
  {
    id: "penguin-inc",
    slug: "penguin-inc",
    title: "Penguin Inc",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Penguin Inc brand landing",
    demo: "https://penguin-inc.vercel.app",
    poster: "/posters/penguin-inc.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#fb923c",
  },
  {
    id: "rolls-royce-las-vegas-luxury-site",
    slug: "rolls-royce-las-vegas-luxury-site",
    title: "Rolls-Royce Las Vegas",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Rolls-Royce Las Vegas luxury marketing",
    demo: "https://rolls-royce-las-vegas-luxury-site.vercel.app",
    poster: "/posters/rolls-royce-las-vegas-luxury-site.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#a1a1aa",
  },
  {
    id: "shotline",
    slug: "shotline",
    title: "Shotline",
    category: "SaaS",
    filters: ["SaaS", "Creative", "Landing"],
    tagline: "Shotline production tool",
    demo: "https://shotline.vercel.app",
    poster: "/posters/shotline.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (no public GitHub)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#94a3b8",
  },
  {
    id: "theshadow",
    slug: "theshadow",
    title: "The Shadow",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "The Shadow site",
    demo: "https://theshadow.vercel.app",
    poster: "/posters/theshadow.jpg",
    price: 49,
    stack: "Static HTML capture",
    source: "static-capture (empty repo VegasCryptoAgent/Shadows)",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#ff7a59",
  },
  {
    id: "the-website",
    slug: "the-website",
    title: "The Website",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "Generic 'the website' 6Frame/client site",
    demo: "https://the-website.vercel.app",
    poster: "/posters/the-website.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:VegasCryptoAgent/the-website",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#e8ff6b",
  },
  {
    id: "ultra-mode",
    slug: "ultra-mode",
    title: "Ultra Mode",
    category: "Landing",
    filters: ["Landing", "Creative"],
    tagline: "UltraMode cool landing page",
    demo: "https://ultra-mode.vercel.app",
    poster: "/posters/ultra-mode.jpg",
    price: 49,
    stack: "npm / Node",
    source: "repo:VegasCryptoAgent/UltraMode",
    included: ["Sanitized source ZIP (no live secrets)", "SITEPACK_README + LICENSE", "Personal & client work OK"],
    accent: "#7dd3fc",
  },
]
